### ISSUE TITLE
Please add a CLI export function for the IIQ DBs

### ISSUE THREAD

**Issue by joeszilagyi** [willnx/iiqtools#13]
Basic request:

The ability on CLI (e.g. so it can be ran via cron trivially) to export your full IIQ DB/dataset to a target location, such as an NFS export.

`[command] [full export] [nfs:/target]`

^ that sort of basic usage, and an inverse "`[full import]`" capability.

**Comment by willnx** [comment]
That's a great idea! Let me poke around the IIQ source to see what could be "reused" by the GUI implementation (come on usable API).

**Comment by willnx** [comment]
Good news! There's a very straight forward API in InsightIQ for this, so creating a CLI tool should be pretty easy.

@joeszilagyi I'd like your input on the CLI syntax. The API requires that the caller supply the cluster(s) to export, and the location (plus FQDN/IP if exporting to an NFS mount). I feel like being able to list the clusters from the CLI tool would be handy too. Having said all that, what do you think about this kind of syntax?

```
usage: iiq_cluster_backup [-h] (--show-clusters | -c CLUSTERS [CLUSTERS ...])
               [-l LOCATION]

Create an archive file of your cluster data

optional arguments:
  -h, --help            show this help message and exit
  --show-clusters       Show the clusters that can be backed up
  -c CLUSTERS [CLUSTERS ...], --clusters CLUSTERS [CLUSTERS ...]
                        The clusters to backup
  -l LOCATION, --location LOCATION
                        where to save the archive file
```

So, to list clusters, you'd just
` iiq_cluster_backup --show-clusters`

And export to the local filesystem, you'd
`iiq_cluster_backup --clusters myCluster --location /some/path`

or
`iiq_cluster_backup --clusters isi01 isi02 --location 10.7.2.1:/ifs/data/iiq_backups`

**Comment by joeszilagyi** [comment]
That seems pretty solid and straightforward for users. What would be the reverse syntax, for importing a given backup export? Add a `--restore` option at the end, require an interactive `yes/no/you sure?` sanity check?

**Comment by willnx** [comment]
I feel like a CLI version of import is more feature creep than useful functionality. I can see a use case for automating a regular backup; clicking though the UI with something like [Selenium](http://www.seleniumhq.org) would be painful and fragile. I don't think it's too much to ask a user to _"login to the UI and delete and restore from backup that cluster..."_ because it should be a rare thing. 

The only thing I can remotely think of is some sort of weird history hack thing. Like, a user tries to define a period of time _vis-a-vis_ a backup, and use the `--restore`  function to look a specific period of time, all in the hopes of saving some disk space. That sounds more like a feature for IIQ than a tool to help make supporting it easier.

Please let me know if you had a use-case in mind for `--restore` that I'm totally blanking on. I'd be happy to work that into the request provided it makes supporting IIQ easier.

**Comment by willnx** [comment]
After doing some initial implementation, and then testing, I've hit a wall.
Turns out, I'll have to add two more CLI arguments to make this even work:

```
--username     The username of an Administrator of the InsightIQ application
--password      Optional - If not supplied, prompt for the password of the Administrator
```

I don't like this solution because it makes `cron`ing the tool problematic, because the password for an Administrator would have to be stored in clear text.
The only thing saving this idea from being utterly insane is the POSIX permissions on the cron directory and cron files:
```
[administrator@localhost ~]$ sudo ls -l /var/spool/cron/
total 8
-rw-------. 1 administrator administrator 10 Feb 15 10:10 administrator
-rw-------. 1 root          root          45 Mar 23  2016 root
[administrator@localhost ~]$ sudo ls -ld /var/spool/cron/
drwx------. 2 root root 4096 Feb 15 10:10 /var/spool/cron/
```

The `administrator` account (yeah, not confusing at all, right)  is required for InsightIQ, and is the de facto Administrator of the system. Because of how that user account is defined, it's basically `root` by a different name. Users could opt to create a non-privledged local user on the CentOS/RHEL box, which would be an Administrator of the InsightIQ application and avoid the whole "root by another name thing," but I still don't like the clear text aspect.

**Comment by willnx** [comment]
I'm going to wrap up implementing this by leveraging [requests](http://docs.python-requests.org/en/master/) to address the "requires admin" aspect of the IIQ API for generating a backup.

Any Administrator of IIQ would work vis-a-vis this tool, but I'll call out in the docs for IIQTools that it's recommend to make a non-privileged local user when automating the backups via a crontab.
