### ISSUE TITLE
Backup filename doesn't include cluster name

### ISSUE THREAD

**Issue by berniecase** [willnx/iiqtools#33]
Right now the backup file is insightiq_export_<epoch>.zip. I'd like to see cluster name included in that filename.

Current example:
insightiq_export_1535747560.zip

Rename it to this:
insightiq_export_cluster_1535747560.zip

I think this name comes from IIQ when it does the export, but perhaps iiqtools could either wait for the export command to complete and then immediately rename, or do something similar by way of a check that'd run out of cron (add entry to cron to check, if command is done, rename the zip file).

**Comment by willnx** [comment]
Sounds like this feature request is to solve the _"what clusters are in this backup file"_ question.
I'm not a big fan of putting the name of the cluster(s) into the file; feels like that will get messy very fast. Plus, you would have to convert the file name _back_ in order to import it into InsightIQ (IIQ expects a particular naming convention of the file in order to do the import).

If we're just trying to solve the _"what clusters are in this backup file"_ question, what about a new argument to `iiqtools_cluster_backup`? Something that will output the different clusters within the file?
My first thought is something like:

    iiqtools_cluster_backup --inspect <backup file>

It could output the name of each cluster, and probably the size/amount of data that cluster has within the backup file. It would also avoid the _can't import it now_ problem that renaming the file will create.

**Comment by berniecase** [comment]
The resulting file is a zip file. Just rename the file after the export is done? It wouldn’t change anything within the zip archive so IIQ would be unaffected. 

We don’t really need another tool to figure out which cluster was backed up. If it was in the zip file name we’d just be able to know by running ls.

**Comment by willnx** [comment]
You'll have to _name it back_ to import it into InsightIQ.

Like, IIQ expects a `.zip` file with the naming schema of `insightiq_export_<time>.zip`. So the logic in IIQ that shows you the files you can import filters out files in the directory that _don't match that pattern_. This alone is enough for me to not put the cluster(s) name in the export file name. Not to mention that the `iiqtools_cluster_backup` script would have to be changed to _run the whole time_ a backup is happening & the file names can get rather long when you have 8 clusters.

This is why I think a new argument is a good compromise. I can see admins going _"why can't IIQ import this backup I made with IIQTools!?"_ because it wont be obvious, and we can't change IIQ.

**Comment by willnx** [comment]
I just merged #35 to address this issue, which adds the `--inspect` argument. Between that, and our conversation _"off line"_ about putting each cluster in a different subdirectory, I feel like this issue is resolved. 

Please let me know if there's more I can do (i.e. just reopen this issue). Thanks @berniecase for the great feedback on IIQTools! 😄
